/**
 * Generates Obsidian-compatible markdown files from BD tasks.
 * Called after BD task IPC operations to keep the vault in sync.
 *
 * Generates:
 *   - Tasks-Overview.md (root) — all active tasks sorted by priority
 *   - Areas/{Deal}/Tasks.md — per-deal task lists
 */
import fs from 'fs';
import path from 'path';
import os from 'os';

import {
  getBdTasksByDeal,
  getBdTasksByStatus,
  getOverdueBdTasks,
  getTopBdTasks,
} from './db.js';
import { logger } from './logger.js';
import { BdTaskWithPriority } from './types.js';

const VAULT_PATH =
  process.env.OBSIDIAN_VAULT_PATH || '/Users/Shared/obsidian-vault';

function priorityLabel(score: number): string {
  if (score >= 80) return '🔴';
  if (score >= 60) return '🟠';
  if (score >= 40) return '🟡';
  return '⚪';
}

function statusEmoji(status: string): string {
  switch (status) {
    case 'open':
      return '⬜';
    case 'in_progress':
      return '🔵';
    case 'waiting':
      return '⏳';
    case 'done':
      return '✅';
    case 'cancelled':
      return '❌';
    default:
      return '⬜';
  }
}

function formatTask(t: BdTaskWithPriority, includeDetail: boolean): string {
  const pri = Math.round(t.computed_priority);
  const icon = priorityLabel(pri);
  const status = statusEmoji(t.status);
  const due = t.due_date ? ` 📅 ${t.due_date.split('T')[0]}` : '';
  const contact = t.contact ? ` — ${t.contact}` : '';
  const tags = t.tags
    ? ` ${JSON.parse(t.tags)
        .map((tag: string) => `#${tag}`)
        .join(' ')}`
    : '';

  let line = `- ${status} ${icon} **${t.title}** (${pri})${contact}${due}${tags}`;

  if (includeDetail) {
    if (t.description) line += `\n  - ${t.description}`;
    if (t.notes) line += `\n  - _${t.notes}_`;
  }

  return line;
}

function formatDate(): string {
  return new Date().toISOString().replace('T', ' ').split('.')[0];
}

function writeIfChanged(filePath: string, content: string): boolean {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  try {
    const existing = fs.readFileSync(filePath, 'utf-8');
    // Compare ignoring the "Last updated" line
    const stripUpdated = (s: string) =>
      s.replace(/^> Last updated:.*$/m, '').trim();
    if (stripUpdated(existing) === stripUpdated(content)) return false;
  } catch {
    // File doesn't exist yet
  }
  fs.writeFileSync(filePath, content);
  return true;
}

function generateOverview(): string {
  const allTasks = getTopBdTasks(50);
  const overdue = getOverdueBdTasks();

  let md = `---
tags: [tasks, auto-generated]
---
# Tasks Overview

> Last updated: ${formatDate()}
> Auto-generated by Andy — do not edit manually

`;

  if (overdue.length > 0) {
    md += `## 🔴 Overdue\n\n`;
    for (const t of overdue) {
      md += formatTask(t, true) + '\n';
    }
    md += '\n';
  }

  // Group by priority tier
  const urgent = allTasks.filter(
    (t) => t.computed_priority >= 80 && !overdue.find((o) => o.id === t.id),
  );
  const important = allTasks.filter(
    (t) => t.computed_priority >= 60 && t.computed_priority < 80,
  );
  const normal = allTasks.filter(
    (t) => t.computed_priority >= 40 && t.computed_priority < 60,
  );
  const low = allTasks.filter((t) => t.computed_priority < 40);

  if (urgent.length > 0) {
    md += `## 🔴 Urgent (80+)\n\n`;
    for (const t of urgent) md += formatTask(t, true) + '\n';
    md += '\n';
  }

  if (important.length > 0) {
    md += `## 🟠 Important (60-79)\n\n`;
    for (const t of important) md += formatTask(t, true) + '\n';
    md += '\n';
  }

  if (normal.length > 0) {
    md += `## 🟡 Normal (40-59)\n\n`;
    for (const t of normal) md += formatTask(t, false) + '\n';
    md += '\n';
  }

  if (low.length > 0) {
    md += `## ⚪ Low (<40)\n\n`;
    for (const t of low) md += formatTask(t, false) + '\n';
    md += '\n';
  }

  if (allTasks.length === 0) {
    md += '_No active tasks._\n';
  }

  return md;
}

function generateDealTasks(deal: string): string {
  const tasks = getBdTasksByDeal(deal);
  const done = getBdTasksByStatus('done').filter((t) => t.deal === deal);

  let md = `---
tags: [tasks, ${deal.toLowerCase()}, auto-generated]
---
# ${deal} — Tasks

> Last updated: ${formatDate()}
> Auto-generated by Andy — do not edit manually

`;

  if (tasks.length === 0 && done.length === 0) {
    md += '_No tasks for this deal._\n';
    return md;
  }

  if (tasks.length > 0) {
    md += `## Active\n\n`;
    for (const t of tasks) md += formatTask(t, true) + '\n';
    md += '\n';
  }

  // Show recent completions (last 10)
  if (done.length > 0) {
    const recent = done.slice(0, 10);
    md += `## Recently Completed\n\n`;
    for (const t of recent) md += formatTask(t, false) + '\n';
    md += '\n';
  }

  return md;
}

/**
 * Regenerate all BD task markdown files in the Obsidian vault.
 * Safe to call frequently — only writes if content actually changed.
 */
export function regenerateBdTaskMarkdown(): void {
  if (!fs.existsSync(VAULT_PATH)) {
    logger.debug(
      { vaultPath: VAULT_PATH },
      'Obsidian vault not found, skipping markdown generation',
    );
    return;
  }

  try {
    // Overview file at vault root
    const overviewPath = path.join(VAULT_PATH, 'Tasks-Overview.md');
    const overviewChanged = writeIfChanged(overviewPath, generateOverview());

    // Per-deal files in Areas/{Deal}/Tasks.md
    const areasDir = path.join(VAULT_PATH, 'Areas');
    let dealFilesChanged = 0;

    if (fs.existsSync(areasDir)) {
      const dealDirs = fs.readdirSync(areasDir).filter((d) => {
        try {
          return fs.statSync(path.join(areasDir, d)).isDirectory();
        } catch {
          return false;
        }
      });

      for (const deal of dealDirs) {
        const dealTasksPath = path.join(areasDir, deal, 'Tasks.md');
        const content = generateDealTasks(deal);
        if (writeIfChanged(dealTasksPath, content)) dealFilesChanged++;
      }
    }

    if (overviewChanged || dealFilesChanged > 0) {
      logger.info(
        { overviewChanged, dealFilesChanged },
        'BD task markdown files updated in Obsidian vault',
      );
    }
  } catch (err) {
    logger.error({ err }, 'Error generating BD task markdown');
  }
}
